### ISSUE TITLE
Bot does not allow users to invite it

### ISSUE THREAD

**Issue by girlyguppy** [NotNorom/banner-changer#1]
can you please let us add it?

**Comment by NotNorom** [comment]
sorry, I disabled it cuz it broke

**Comment by girlyguppy** [comment]
Can you fix it? Or any recommendations to another like it?

**Comment by NotNorom** [comment]
I am working on a new bot that should replace this one. It's like... halfway done. I think it should be working at the end of October.
You can follow development here: https://github.com/NotNorom/discord-banner-bot

**Comment by girlyguppy** [comment]
Ok, cool

**Comment by NotNorom** [comment]
New bot is working. See https://github.com/NotNorom/discord-banner-bot
